# Generated by Django 5.0.4 on 2024-04-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_for_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_1',
            field=models.ImageField(default=1, upload_to='Article/'),
            preserve_default=False,
        ),
    ]
